add jacky and liqun to archinfra approvers
onnx/sigs pull request #119
Opened 2022-03-24 00:49 UTC by liqunfu

Signed-off-by: Liqun Fu <liqfu@microsoft.com>

2022-03-24 15:00 UTC, garymm requested changes

2022-03-24 15:00 UTC, garymm commented on CONTRIBUTORS
> +        - jcwchen
Please remove from contributors lists above

2022-03-24 15:00 UTC, garymm commented on CONTRIBUTORS
> +        - liqunfu
please keep sorted alphabetically

2022-03-29 20:07 UTC, garymm approved these changes

2022-03-30 20:42 UTC, liqunfu commented
@prasanthpul , please approve this if it is ok.

2022-04-05 17:17 UTC, askhade approved these changes

2022-04-05 18:40 UTC, AlexandreEichenberger approved these changes
LGTM

2022-04-06 22:02 UTC, merged